/**
 * Shop Catalog — defines all purchasable items.
 * IDs must be stable (used as keys in inventory).
 */

export const BALLOON_SKINS = [
  {
    id: "default",
    label: "Classic Red",
    emoji: "🎈",
    preview: "#ef4444",
    price: 0,
    desc: "The original. Always in style.",
    free: true,
  },
  {
    id: "neon_purple",
    label: "Neon Purple",
    emoji: "🫧",
    preview: "#a855f7",
    price: 300,
    desc: "Electric violet glow on every balloon.",
  },
  {
    id: "golden_hour",
    label: "Golden Hour",
    emoji: "⭐",
    preview: "#eab308",
    price: 500,
    desc: "All balloons shimmer in gold.",
  },
  {
    id: "ocean_breeze",
    label: "Ocean Breeze",
    emoji: "🫐",
    preview: "#38bdf8",
    price: 450,
    desc: "Cool cyan tones across the board.",
  },
  {
    id: "cherry_blossom",
    label: "Cherry Blossom",
    emoji: "🌸",
    preview: "#f472b6",
    price: 600,
    desc: "Soft pink petals raining down.",
  },
  {
    id: "midnight",
    label: "Midnight",
    emoji: "🌙",
    preview: "#1e293b",
    price: 750,
    desc: "Dark, mysterious, impossible to ignore.",
  },
  {
    id: "fire",
    label: "Inferno",
    emoji: "🔥",
    preview: "#f97316",
    price: 900,
    desc: "Red-hot flame color palette.",
  },
  {
    id: "rainbow",
    label: "Rainbow Burst",
    emoji: "🌈",
    preview: "rainbow",
    price: 1200,
    desc: "Each balloon gets a different color!",
    rare: true,
  },
];

export const WHEEL_THEMES = [
  {
    id: "default",
    label: "Classic Casino",
    emoji: "🎡",
    price: 0,
    desc: "The standard spin wheel.",
    free: true,
    colors: ["#ef4444", "#f97316", "#eab308", "#22c55e", "#3b82f6", "#a855f7", "#ec4899", "#14b8a6"],
  },
  {
    id: "galaxy",
    label: "Galaxy",
    emoji: "🌌",
    price: 400,
    desc: "Deep space colors — stars included.",
    colors: ["#1e1b4b", "#312e81", "#4338ca", "#6366f1", "#818cf8", "#a5b4fc", "#c7d2fe", "#e0e7ff"],
  },
  {
    id: "tropical",
    label: "Tropical",
    emoji: "🌴",
    price: 350,
    desc: "Bright beach vibes all day.",
    colors: ["#22c55e", "#84cc16", "#eab308", "#f97316", "#ef4444", "#ec4899", "#06b6d4", "#a855f7"],
  },
  {
    id: "sunset",
    label: "Sunset Glow",
    emoji: "🌅",
    price: 500,
    desc: "Warm gradient dusk palette.",
    colors: ["#fef3c7", "#fde68a", "#fbbf24", "#f97316", "#ef4444", "#dc2626", "#b91c1c", "#7f1d1d"],
  },
  {
    id: "emerald",
    label: "Emerald City",
    emoji: "💎",
    price: 600,
    desc: "Rich jewel-tone greens and golds.",
    colors: ["#064e3b", "#065f46", "#047857", "#059669", "#10b981", "#34d399", "#6ee7b7", "#a7f3d0"],
    rare: true,
  },
  {
    id: "monochrome",
    label: "Monochrome",
    emoji: "🖤",
    price: 700,
    desc: "Sleek black and white precision.",
    colors: ["#0f172a", "#1e293b", "#334155", "#475569", "#64748b", "#94a3b8", "#cbd5e1", "#f1f5f9"],
    rare: true,
  },
];

export const DART_POWERUPS = [
  {
    id: "multishot",
    label: "Multi-Shot",
    emoji: "🔱",
    price: 150,
    desc: "Fires 3 darts at once.",
    stackable: true,
    maxOwn: 5,
  },
  {
    id: "mirv",
    label: "MIRV Bomb",
    emoji: "💥",
    price: 200,
    desc: "Explodes into cluster darts mid-flight.",
    stackable: true,
    maxOwn: 5,
  },
  {
    id: "sniper",
    label: "Sniper",
    emoji: "🎯",
    price: 175,
    desc: "Pierces through 5 balloons & obstacles.",
    stackable: true,
    maxOwn: 5,
  },
  {
    id: "freeze",
    label: "Freeze",
    emoji: "❄️",
    price: 225,
    desc: "Freezes all balloons for 3 seconds.",
    stackable: true,
    maxOwn: 5,
  },
  {
    id: "gravity",
    label: "Gravity Bomb",
    emoji: "🌀",
    price: 250,
    desc: "Pulls balloons together then pops them.",
    stackable: true,
    maxOwn: 5,
  },
  {
    id: "zipper",
    label: "The Zipper",
    emoji: "⚡",
    price: 300,
    desc: "Bounces off everything, speeds up on every hit.",
    stackable: true,
    maxOwn: 5,
  },
];